#!/usr/bin/env bash
# Generate TypeScript types from src/interact/api_types.py.
# Output is checked in (vscode-extension/src/generated/types.ts) so the
# extension can build without invoking Python.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
EXT_DIR="$(dirname "$HERE")"
REPO_DIR="$(dirname "$EXT_DIR")"
OUT="$EXT_DIR/src/generated/types.ts"

mkdir -p "$(dirname "$OUT")"

cd "$REPO_DIR"

# pydantic2ts shells out to `json2ts`; ensure the local node_modules bin is on PATH.
export PATH="$EXT_DIR/node_modules/.bin:$PATH"

if ! uv run --directory "$REPO_DIR" python -c "import pydantic2ts" >/dev/null 2>&1; then
    echo "[generate-types] pydantic-to-typescript not installed; skipping." >&2
    exit 0
fi

uv run --directory "$REPO_DIR" pydantic2ts \
    --module interact.api_types \
    --output "$OUT"

# Prepend header if pydantic2ts didn't add one.
if ! head -1 "$OUT" | grep -q "generated"; then
    HEADER="// AUTO-GENERATED by vscode-extension/scripts/generate-types.sh.\n// Source: src/interact/api_types.py. Do not edit by hand.\n"
    printf "%b%s" "$HEADER" "$(cat "$OUT")" > "$OUT"
fi

echo "[generate-types] wrote $OUT" >&2
