#!/usr/bin/env bash
# Generate TypeScript types from src/interact/api_types.py.
# Output is checked in (clients/vscode/src/generated/types.ts) so the
# extension can build without invoking Python.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
EXT_DIR="$(dirname "$HERE")"
REPO_DIR="$(dirname "$(dirname "$EXT_DIR")")"
OUT="$EXT_DIR/src/generated/types.ts"

mkdir -p "$(dirname "$OUT")"

cd "$REPO_DIR"

# pydantic2ts shells out to `json2ts`; ensure the local node_modules bin is on PATH.
export PATH="$EXT_DIR/node_modules/.bin:$PATH"
# Schema generation imports the model catalog. Keep that build step on bundled data: compiling
# the extension must never refresh LiteLLM pricing or probe a configured Ollama account.
export LITELLM_LOCAL_MODEL_COST_MAP="True"
export OLLAMA_DISCOVERY="0"

# Prefer the sibling checkout while developing in the private parent. A public checkout without
# that sibling must resolve the released dependency instead of treating a missing local path as
# the package source.
CORE_SOURCE_DIR="$REPO_DIR/../interact-core"
UV_RUN=(uv run --directory "$REPO_DIR")
if [ -f "$CORE_SOURCE_DIR/pyproject.toml" ]; then
    UV_RUN+=(--with-editable "$CORE_SOURCE_DIR")
fi

if ! "${UV_RUN[@]}" python -c "import pydantic2ts" >/dev/null 2>&1; then
    echo "[generate-types] pydantic-to-typescript not installed; skipping." >&2
    exit 0
fi

# The public repository consumes the released package. When both repositories are checked out
# under the private parent, regenerate the sibling's checked-in schema artifacts; an installed
# core package is read-only and already carries its release schemas.
CORE_SCHEMA_DIR="${INTERACT_CORE_SCHEMA_DIR:-$CORE_SOURCE_DIR/src/interact_core/schema}"
if [ ! -f "$CORE_SOURCE_DIR/pyproject.toml" ] || [ ! -d "$CORE_SCHEMA_DIR" ]; then
    CORE_SCHEMA_DIR=""
fi

"${UV_RUN[@]}" pydantic2ts \
    --module interact.api_types \
    --output "$OUT"
"${UV_RUN[@]}" pydantic2ts \
    --module interact_core.prompts \
    --output "$EXT_DIR/src/generated/promptContracts.ts"
if [ -n "$CORE_SCHEMA_DIR" ]; then
    "${UV_RUN[@]}" python "$HERE/export-prompt-schema.py" \
        > "$CORE_SCHEMA_DIR/prompt-contracts.schema.json"
    "${UV_RUN[@]}" python "$HERE/export-account-schema.py" \
        > "$CORE_SCHEMA_DIR/account-contracts.schema.json"
    "${UV_RUN[@]}" python "$HERE/export-workflow-schema.py" \
        > "$CORE_SCHEMA_DIR/workflow-contracts.schema.json"
    "${UV_RUN[@]}" python "$HERE/export-admin-schema.py" \
        > "$CORE_SCHEMA_DIR/admin-contracts.schema.json"
else
    echo "[generate-types] installed interact-core detected; keeping its packaged schemas unchanged." >&2
fi
SCHEMA_OUT="$EXT_DIR/out/generated/conversation-schemas.json"
mkdir -p "$(dirname "$SCHEMA_OUT")"
"${UV_RUN[@]}" python "$HERE/export-runtime-schemas.py" > "$SCHEMA_OUT"
node "$HERE/append-runtime-decoders.js" "$SCHEMA_OUT"

# Prepend header if pydantic2ts didn't add one.
if ! head -1 "$OUT" | grep -q "generated"; then
    HEADER="// AUTO-GENERATED by clients/vscode/scripts/generate-types.sh.\n// Source: src/interact/api_types.py. Do not edit by hand.\n"
    printf "%b%s" "$HEADER" "$(cat "$OUT")" > "$OUT"
fi

echo "[generate-types] wrote $OUT" >&2
