#!/usr/bin/env bash
# Generate TypeScript types from packages/interact-local/src/interact/api_types.py.
# Output is checked in (clients/vscode/src/generated/types.ts) so the
# extension can build without invoking Python.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
EXT_DIR="$(dirname "$HERE")"
REPO_DIR="$(dirname "$(dirname "$EXT_DIR")")"
OUT="$EXT_DIR/src/generated/types.ts"

mkdir -p "$(dirname "$OUT")"

cd "$REPO_DIR"

# pydantic2ts shells out to `json2ts`; ensure the local node_modules bin is on PATH.
export PATH="$EXT_DIR/node_modules/.bin:$PATH"
# Schema generation imports the model catalog. Keep that build step on bundled data: compiling
# the extension must never refresh LiteLLM pricing or probe a configured Ollama account.
export LITELLM_LOCAL_MODEL_COST_MAP="True"
export OLLAMA_DISCOVERY="0"

if ! uv run --directory "$REPO_DIR" python -c "import pydantic2ts" >/dev/null 2>&1; then
    echo "[generate-types] pydantic-to-typescript not installed; skipping." >&2
    exit 0
fi

uv run --directory "$REPO_DIR" pydantic2ts \
    --module interact.api_types \
    --output "$OUT"
uv run --directory "$REPO_DIR" pydantic2ts \
    --module interact_core.prompts \
    --output "$EXT_DIR/src/generated/promptContracts.ts"
uv run --directory "$REPO_DIR" python "$HERE/export-prompt-schema.py" \
    > "$REPO_DIR/packages/interact-core/schema/prompt-contracts.schema.json"
SCHEMA_OUT="$EXT_DIR/out/generated/conversation-schemas.json"
mkdir -p "$(dirname "$SCHEMA_OUT")"
uv run --directory "$REPO_DIR" python "$HERE/export-runtime-schemas.py" > "$SCHEMA_OUT"
node "$HERE/append-runtime-decoders.js" "$SCHEMA_OUT"

# Prepend header if pydantic2ts didn't add one.
if ! head -1 "$OUT" | grep -q "generated"; then
    HEADER="// AUTO-GENERATED by clients/vscode/scripts/generate-types.sh.\n// Source: packages/interact-local/src/interact/api_types.py. Do not edit by hand.\n"
    printf "%b%s" "$HEADER" "$(cat "$OUT")" > "$OUT"
fi

echo "[generate-types] wrote $OUT" >&2
